name: Bump version
on:
  push:
    branches: [main]
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - 'CHANGELOG.md'
      - 'dist/**/*'
  workflow_dispatch: # Allow manual invocation of the workflow

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: install conventional-changelog dependency
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Bump version and push tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GH_SECRET_TOKEN }}
          git-message: 'chore(release): {version}'
          release-count: 0
          git-user-name: 'YOYODev'
          git-user-email: 'developer@yoyo-holdings.com'
          skip-on-empty: false
          output-file: 'false'
          config-file-path: '.versionrc.js'
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
